#framework:
#    default_locale: '%locale%'
#    translator:
#        default_path: '%kernel.project_dir%/translations'
#        fallbacks:
#            - '%locale%'
framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - 'en'
            - 'it'
            - 'fr'